
const s = "360ONE,AADHARHFC,AARTIDRUGS,5PAISA,20MICRONS,AARON,3IINFOLTD,AAREYDRUGS,AARTECH,3PLAND,ABB,ABCAPITAL,ACC,ABSLAMC,ABREL,ABDL,ABLBL,ABFRL,ABINFRA,ABCOTS,ADANIPORTS,ADANIPOWER,ADANIENT,ADANIENSOL,ACUTAAS,ACMESOLAR,ACI,ADFFOODS,ADOR,ADROITINFO,AEGISLOG,AFFLE,AETHER,AFCONS,AEROFLEX,AGARIND,AFSL,AEROENTER,AFIL,AERONEU,AIIL,AIAENG,AJANTPHARM,AHLUCONT,AJAXENGG,AJMERA,AIROLAM,AJOONI,AKG,AKASH,ALKEM,ALIVUS,ALKYLAMINE,ALLTIME,ALLCARGO,ALICON,ALLDIGI,AMANTA,ALMONDZ,ALPA,AMBUJACEM,ANGELONE,ANANDRATHI,ANANTRAJ,AMRUTANJAN,ANDHRAPAP,ANDHRSUGAR,AMNPLST,AMBIKCO,AMJLAND,APOLLOHOSP,APLAPOLLO,APARINDS,APOLLOTYRE,APLLTD,APOLLO,APCOTEXIND,APEX,APOLLOPIPE,APOLSINHOT";
const list = s.split(',');
console.log('Is ARE in list?', list.includes('ARE'));
console.log('Indices containing ARE:', list.filter(t => t.includes('ARE')));
